version: '3'

services:
  api:
    container_name: gs-api
    build: ./server
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - PORT=3000
    volumes:
      - ./books:/usr/src/app/books
    networks:
      - services

  bookscraper:
    container_name: gs-bookscraper
    build: ./bookscraper
    networks:
      - services

  frontend:
    container_name: gs_frontend
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "8080:80"

  elasticsearch:
    container_name: gs_search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - services

  db:
    container_name: gs_db
    image: postgres
    ports:
      - "1234:1234"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - services

networks:
  services:
    driver: bridge

volumes:
  esdata:
